name: Keep Bot Alive for Active Developer Badge

on:
  schedule:
    # Jalankan setiap 25 hari sekali
    - cron: "0 0 */25 * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST $RENDER_DEPLOY_HOOK
          echo "🚀 Bot redeployed successfully!"

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Livales Bot - Active Developer Badge Maintained"
          to: alifsuryadi037@gmail.com
          from: Livales Bot Notifier
          body: |
            Hi!

            Your Livales Discord Bot has been automatically redeployed to maintain your Active Developer Badge.

            Details:
            - Deployment Time: ${{ steps.current-time.outputs.time }}
            - Next Deployment: In 25 days
            - Bot Status: Active ✅

            Important Reminders:
            - Make sure to use at least one slash command in your Discord server
            - Check if the bot is online in Discord
            - Your Active Developer Badge is safe! 🎉

            Dashboard Links:
            - Render Dashboard: https://dashboard.render.com
            - Discord Developer Portal: https://discord.com/developers/applications

            Best regards,
            Livales Bot Automation
